export const FETCH_USER_DETAILS = "USER/DETAILS";
export const FETCH_USER_POINTS = "USER/POINTS";
export const FETCH_PRODUCTS_BY_USER = "USER/PRODUCTS";
export const FETCH_PRODUCTS = "PRODUCTS/LIST";
export const ERROR = "ERROR";
export const LOADING = "LOADING";
export const UPDATE_SUCCESS_MESSAGE = "SUCCESS_MESSAGE/UPDATE";
